{{ if .Values.green.additionalconfiguration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-additional-config-green
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "ocp-nginx-bluegreen.name" . }}
    version: {{ .Values.green.appVersion | quote }}
data:
  default.conf: {{ .Values.green.additionalconfiguration | quote }}
{{ end }}
